name: Build & deploy service

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths-ignore:
    - 'src/Shared/**'
    - 'src/Jobs/**'
    - 'README.ME'
    - 'doc/**'
    - 'test/**'

jobs:
  build-service-in-dev:
    uses: ./.github/workflows/.script-build-service-docker-image-and-push-into-acr.yml
    with:
      ENVIRONMENT_TYPE: demo
      PROJECT_NAME: cloudtrack
      SERVICE_NAME: compet
      DOCKERFILE_PATH: ./src/CloudTrack.Competitions.WebAPI/Dockerfile
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-service-in-dev:
    uses: ./.github/workflows/.script-deploy-service-into-aca.yml
    needs: build-service-in-dev
    with:
      ENVIRONMENT_TYPE: demo
      RESOURCE_GROUP: ${{ vars.AZURE_GROUP }}
      PROJECT_NAME: cloudtrack
      SERVICE_NAME: compet
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
